# 1. Numpy基础
## 1.1 Ndarray 对象
numpy中的ndarray对象是一个多维数组对象，它是一系列同类型数据的集合，索引从0开始。
ndarray对象时用于存放同类型元素的多维数组；
ndarray中的每个元素在内存中都有相同存储大小的区域；
ndarray内部有以下内容组成：
- 一个只想数据的（内存或内存映射文件中的一块数据）的指针；
- 数据类型或dtype，描述在数组中的固定大小值得格子；
- 一个表示数组形状（shape）的元组，表示各维度大小的元组；
- 一个跨度元组（stride），其中的整数指的是为了前进到当前维度下一个元素需要跨过的字节数，跨度可以是负数。

## 1.2 创建ndarray对象
> 创建一个ndarray对象的最简单方法是使用numpy.array()函数。

```python
import numpy as np

np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

**参数说明**：
|名称|说明|
|:--|:--|
|object|要转换为ndarray对象的对象，可以是列表、元组、数组等|
|dtype|数据类型，指定ndarray对象中元素的数据类型|
|copy|是否复制对象|
|order|创建数组得样式，'C'表示行优先，'F'表示列优先，'A'为任意方向|
|subok|是否返回子类|
|ndmin|指定ndarray对象的最小维数|

实例如下：

In [16]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [17]:
import numpy as np

b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [18]:
import numpy as np

c = np.array([1, 2, 3, 4, 5, 6], ndmin=2)
print(c)
print(c.shape)

c = c.reshape(3, 2)
print(c)
print(c.shape)
print(c[0, 1])

[[1 2 3 4 5 6]]
(1, 6)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [19]:
import numpy as np

d = np.array([1, 2, 3], dtype=np.float32)
print(d)
print(d.dtype)

d = d.astype(np.int32)
print(d)
print(d.dtype)

d = d.astype(np.float64)
print(d)
print(d.dtype)

d = d.astype(complex)
print(d)
print(d.dtype)

[1. 2. 3.]
float32
[1 2 3]
int32
[1. 2. 3.]
float64
[1.+0.j 2.+0.j 3.+0.j]
complex128


ndarray 对象由计算机内存的连续一维部分组成，并结合索引模式，将每个元素映射到内存块中的一个位置。内存块以行顺序（C样式）或列顺序（Fortran样式或Matlab风格）存储。

## 1.3 numpy数据类型
numpy支持的数据类型比python内置数据类型要多，numpy中的数据类型有：
|名称|说明|取值范围|
|:--|:--|:--|
|bool_|布尔型|True或False|
|int_|整数型|-2^31~2^31-1|
|intp|整数型|与平台相关，32位或64位|
|int8|整数型|-128~127|
|int16|整数型|-32768~32767|
|int32|整数型|-2147483648~2147483647|
|int64|整数型|-9223372036854775808~9223372036854775807|
|uint8|无符号整数型|0~255|
|uint16|无符号整数型|0~65535|
|uint32|无符号整数型|0~4294967295|
|uint64|无符号整数型|0~18446744073709551615|
|float_|浮点型|与平台相关，32位或64位|
|float16|浮点型|半精度，1位符号位，5位指数位，10位尾数位|
|float32|浮点型|单精度，1位符号位，8位指数位，23位尾数位|
|float64|浮点型|双精度，1位符号位，11位指数位，52位尾数位|
|complex_|复数型|与平台相关，32位或64位|
|complex64|复数型|单精度，1位符号位，8位指数位，23位尾数位|
|complex128|复数型|双精度，1位符号位，11位指数位，52位尾数位|
|str_|字符串型|长度不定|

#### 数据类型对象（dtype）
数据类型对象（numpy.dtype类的实例）用来描述与数组对应地内存区域时如何使用，它描述了数据的以下几个方面：
- 数据类型（整数、浮点数、或python对象）
- 数据的大小（如整数使用多少个字节存储）
- 数据的字节顺序（大端或小端）
- 在结构化类型的情况下，字段的名称、每个字段的数据类型和每个字段所取得内存块的部分
- 如果数据类型是子数组，那么它的形状和数据类型是什么

字节顺序通过对数据类型预设`>`、`<`来决定，