# Pytorch 张量（Tensor）基础

张量是一个多维数组。
在 PyTorch 中，张量是数据的核心表示形式，类似于Numpy中的ndarray。但具有GPU加速的能力。

张量支持多种数据类型（整型、浮点型、布尔型等），并且可以在 CPU 和 GPU 之间进行转换。

张量的维度称为“轴”（axis），每个轴的大小称为“形状”（shape）。例如，一个形状为 (3, 4) 的张量表示有 3 行和 4 列的数据。

![alt text](<assets/different_dimension_tensor.jpg>)

- 0维张量：标量（scalar），例如一个数字 5。
- 1维张量：向量（vector），例如 [1, 2, 3]。
- 2维张量：矩阵（matrix），例如 [[1, 2], [3, 4]]。
- 3维张量：立方体（cube），例如 [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]。
- 4维张量：立方体向量，例如 [[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]。
- 5维张量：立方体矩阵，例如 [[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]], [[[[17, 18], [19, 20]], [[21, 22], [23, 24]]], [[[25, 26], [27, 28]], [[29, 30], [31, 32]]]]]。

## 1. 创建张量

|方法|说明|示例|
|---|---|---|
|`torch.tensor(data)`|从python列表或NumPy数组创建张量|`x = torch.tensor([[1, 2], [3, 4]])`|
|`torch.zeros(size)`|创建全零张量|`x = torch.zeros((2, 3))`|
|`torch.ones(size)`|创建全一张量|`x = torch.ones((2, 3))`|
|`torch.empty(size)`|创建未初始化的张量|`x = torch.empty((2, 3))`|
|`torch.rand(size)`|创建均匀分布的随机张量，值在[0,1)|`x = torch.rand((2, 3))`|
|`torch.randn(size)`|创建正态分布的随机张量，均值为0，标准差为1|`x = torch.randn((2, 3))`|
|`torch.arange(start, end, step)`|创建一个一维张量，包含从start到end（不包括end），步长为step的值|`x = torch.arange(0, 10, 2)`|
|`torch.linspace(start, end, steps)`|创建一个一维张量，包含从start到end（包括end），均匀分布的steps个值|`x = torch.linspace(0, 1, 5)`|
|`torch.eye(n)`|创建一个n x n的单位矩阵|`x = torch.eye(3)`|
|`torch.from_numpy(ndarray)`|从NumPy数组创建张量|`x = torch.from_numpy(np.array([[1, 2], [3, 4]]))`|

使用`torch.tensor()`函数，可以将一个列表或数组转换为张量：

In [1]:
import torch

tensor = torch.tensor([1, 2, 3, 4, 5])
print(tensor)

tensor([1, 2, 3, 4, 5])


如果有一个NumPy数组，可以使用`torch.from_numpy()`函数将其转换为张量：

In [2]:
import numpy as np

np_array = np.array([1, 2, 3, 4, 5])
print(np_array)

tensor = torch.from_numpy(np_array)
print(tensor)

[1 2 3 4 5]
tensor([1, 2, 3, 4, 5])


In [3]:
# create 2D tensor
tensor_2D = torch.tensor([
    [-9, 4, 2, 4],
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("2D tensor (Matrix): \n", tensor_2D)

print("Shape:", tensor_2D.shape)

2D tensor (Matrix): 
 tensor([[-9,  4,  2,  4],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]])
Shape: torch.Size([3, 4])


In [4]:
# create other dimensions
tensor_3D = torch.stack(
    [tensor_2D, tensor_2D + 10, tensor_2D -5]
)

print("3D tensor: \n", tensor_3D)
print("Shape:", tensor_3D.shape)

tensor_4D = torch.stack(
    [tensor_3D, tensor_3D + 10, tensor_3D -5]
)
print("4D tensor: \n", tensor_4D)
print("Shape:", tensor_4D.shape)

# create 5D tensor
tensor_5D = torch.stack(
    [tensor_4D, tensor_4D + 10, tensor_4D -5]
)
print("5D tensor: \n", tensor_5D)
print("Shape:", tensor_5D.shape)

3D tensor: 
 tensor([[[ -9,   4,   2,   4],
         [  1,   2,   3,   4],
         [  5,   6,   7,   8]],

        [[  1,  14,  12,  14],
         [ 11,  12,  13,  14],
         [ 15,  16,  17,  18]],

        [[-14,  -1,  -3,  -1],
         [ -4,  -3,  -2,  -1],
         [  0,   1,   2,   3]]])
Shape: torch.Size([3, 3, 4])
4D tensor: 
 tensor([[[[ -9,   4,   2,   4],
          [  1,   2,   3,   4],
          [  5,   6,   7,   8]],

         [[  1,  14,  12,  14],
          [ 11,  12,  13,  14],
          [ 15,  16,  17,  18]],

         [[-14,  -1,  -3,  -1],
          [ -4,  -3,  -2,  -1],
          [  0,   1,   2,   3]]],


        [[[  1,  14,  12,  14],
          [ 11,  12,  13,  14],
          [ 15,  16,  17,  18]],

         [[ 11,  24,  22,  24],
          [ 21,  22,  23,  24],
          [ 25,  26,  27,  28]],

         [[ -4,   9,   7,   9],
          [  6,   7,   8,   9],
          [ 10,  11,  12,  13]]],


        [[[-14,  -1,  -3,  -1],
          [ -4,  -3,  -2,  -1],
    

## 2. 张量属性
张量有几个重要的属性：

|属性|说明|示例|
|---|---|---|
|.shape|张量的形状|`tensor.shape`|
|.size()|张量的大小|`tensor.size()`|
|.dtype|张量的数据类型|`tensor.dtype`|
|.device|张量所在的设备（CPU或GPU）|`tensor.device`|
|.requires_grad|是否需要梯度计算|`tensor.requires_grad`|
|.numel()|张量的元素个数|`tensor.numel()`|
|.is_cuda|是否在GPU上|`tensor.is_cuda`|
|.is_leaf|是否是叶子节点|`tensor.is_leaf`|
|.T|转置张量|`tensor.T`|
|.item()|获取标量值|`tensor.item()`|
|.is_contiguous()|是否是连续的|`tensor.is_contiguous()`|
|.storage()|返回张量的存储对象|`tensor.storage()`|
|.stride()|返回张量的步幅|`tensor.stride()`|


In [9]:
import torch

# create 2D tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("Original tensor:\n", tensor)

# tensor properties
print("Shape:", tensor.shape)
print("size:", tensor.size())
print("Number of dimensions:", tensor.ndim)
print("Data type:", tensor.dtype)
print("Device:", tensor.device)
print("Number of elements:", tensor.numel())
print("Element size (bytes):", tensor.element_size())
print("Data type:", tensor.dtype)
print("Requires grad:", tensor.requires_grad)
print("Is leaf:", tensor.is_leaf)
print("Is sparse:", tensor.is_sparse)
print("Is quantized:", tensor.is_quantized)
print("Is complex:", tensor.is_complex)
print("Is contiguous:", tensor.is_contiguous())
print("Is CUDA:", tensor.is_cuda)


single_value = torch.tensor(42)
print("Single value tensor:", single_value)

# inverse tensor
tensor_T = tensor.T
print("Transposed tensor:\n", tensor_T)

Original tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])
size: torch.Size([2, 3])
Number of dimensions: 2
Data type: torch.float32
Device: cpu
Number of elements: 6
Element size (bytes): 4
Data type: torch.float32
Requires grad: False
Is leaf: True
Is sparse: False
Is quantized: False
Is complex: <built-in method is_complex of Tensor object at 0x0000024F6CEFEC90>
Is contiguous: True
Is CUDA: False
Single value tensor: tensor(42)
Transposed tensor:
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## 3. 张量操作
张量支持多种操作，包括数学运算、索引、切片、连接等

基础操作：
|操作|说明|示例|
|---|---|---|
|+ - * /|加、减、乘、除|`a + b`, `a - b`, `a * b`, `a / b`|
|torch.matmul(a, b)|矩阵乘法|`z = torch.matmul(a, b)`|
|torch.dot(a, b)|向量点乘，仅适用于1D张量|`z = torch.dot(a, b)`|
|tensor.sum(x)|对张量的所有元素求和|`z = torch.sum(x)`|
|tensor.mean(x)|对张量的所有元素求均值|`z = torch.mean(x)`|
|tensor.max(x)|对张量的所有元素求最大值|`z = torch.max(x)`|
|tensor.min(x)|对张量的所有元素求最小值|`z = torch.min(x)`|
|tensor.argmax(x)|返回最大值的索引，指定维度|`z = torch.argmax(x, dim=1)`|
|tensor.argmin(x)|返回最小值的索引，指定维度|`z = torch.argmin(x, dim=1)`|
|tensor.softmax(x)|计算softmax（指定维度）|`z = torch.softmax(x, dim=1)`|

形状操作：
|操作|说明|示例|
|---|---|---|
|x.view(shape)|改变张量的形状（不改变数据）|`z = x.view(2, 3)`|
|x.reshape(shape)|类似于view，但更灵活|`z = x.reshape(2, 3)`|
|x.t()|转置张量|`z = x.t()`|
|x.unsqueeze(dim)|在指定维度上增加一个维度|`z = x.unsqueeze(0)`|
|x.squeeze(dim)|在指定维度上去掉一个维度|`z = x.squeeze(0)`|
|torch.cat((x, y), dim)|在指定维度上连接两个张量|`z = torch.cat((x, y), dim=0)`|
|torch.stack((x, y), dim)|在指定维度上堆叠两个张量|`z = torch.stack((x, y), dim=0)`|

In [11]:
import torch

# create 2D tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("Original tensor:\n", tensor)

# 1. index and slice operations
print("\nIndexing and slicing:")
print("First row:", tensor[0])
print("First column:", tensor[:, 0])
print("First row and first column:", tensor[0, 0])
print("First two rows:", tensor[:2])
print("Last row:", tensor[-1])
print("Last column:", tensor[:, -1])
print("Last two rows:", tensor[-2:])
print("Last two columns:", tensor[:, -2:])
print("First two rows and first two columns:", tensor[:2, :2])
print("First two rows and last two columns:", tensor[:2, -2:])
print("Last two rows and first two columns:", tensor[-2:, :2])
print("Last two rows and last two columns:", tensor[-2:, -2:])


# 2. shape operations
print("\nShape operations:")
print("Shape:", tensor.shape)

reshaped_tensor = tensor.view(3, 2)
print("Reshaped tensor:\n", reshaped_tensor)

flattened_tensor = tensor.flatten() # make the tensor to 1D
print("Flattened tensor:\n", flattened_tensor)


# 3. math operations
print("\nMath operations:")
tensor_add = tensor + 10
print("Addition 10:\n", tensor_add)

tensor_mul = tensor * 2
print("Multiplication 2:\n", tensor_mul)

tensor_sum = tensor.sum()
print("Sum of all elements:", tensor_sum, tensor_sum.item())

tensor_mean = tensor.mean()
print("Mean of all elements:", tensor_mean, tensor_mean.item())


# 4. other operations
print("\nOther operations:")
tensor2 = torch.tensor([[1, 1, 1], [1, 1, 1]], dtype=torch.float32)
print("Second tensor:\n", tensor2)

tensor_matmul = torch.matmul(tensor, tensor2.T)
print("Matrix multiply result:\n", tensor_matmul)


# 5. conditionals judge and screen
print("\nConditionals and screening:")
mask = tensor > 2          # create a boolean mask
print("The boolean mask of tensor > 2:\n", mask)

filtered_tensor = tensor[mask]  # filter the tensor using the mask
print("Filtered tensor (elements > 2):\n", filtered_tensor)


Original tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

Indexing and slicing:
First row: tensor([1., 2., 3.])
First column: tensor([1., 4.])
First row and first column: tensor(1.)
First two rows: tensor([[1., 2., 3.],
        [4., 5., 6.]])
Last row: tensor([4., 5., 6.])
Last column: tensor([3., 6.])
Last two rows: tensor([[1., 2., 3.],
        [4., 5., 6.]])
Last two columns: tensor([[2., 3.],
        [5., 6.]])
First two rows and first two columns: tensor([[1., 2.],
        [4., 5.]])
First two rows and last two columns: tensor([[2., 3.],
        [5., 6.]])
Last two rows and first two columns: tensor([[1., 2.],
        [4., 5.]])
Last two rows and last two columns: tensor([[2., 3.],
        [5., 6.]])

Shape operations:
Shape: torch.Size([2, 3])
Reshaped tensor:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Flattened tensor:
 tensor([1., 2., 3., 4., 5., 6.])

Math operations:
Addition 10:
 tensor([[11., 12., 13.],
        [14., 15., 16.]])
Multiplication 2:
 tensor(

## 4. 张量的GPU加速
将张量转移到GPU上，并检测是否可用：

In [12]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.tensor([1, 2, 3], device=device, dtype=torch.float32)

torch.cuda.is_available()

False

## 5. 张量与NumPy的互操作
张量和NumPy数组之间可以相互转换：

| 操作 | 说明 | 示例 |
|---|---|---|
| `torch.from_numpy(ndarray)` | 从NumPy数组创建张量 | `tensor = torch.from_numpy(np_array)` |
| `tensor.numpy()` | 将张量转换为NumPy数组（仅限CPU张量） | `np_array = tensor.numpy()` |
| `torch.save(tensor, 'file.pth')` | 保存张量到文件 | `torch.save(tensor, 'tensor.pth')` |
| `torch.load('file.pth')` | 从文件加载张量 | `tensor = torch.load('tensor.pth')` |

In [13]:
import torch
import numpy as np

# 1. numpy ndarray to torch tensor
print("1. Numpy ndarray to torch tensor:")
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Numpy array:\n", numpy_array)
torch_tensor = torch.from_numpy(numpy_array)
print("Torch tensor:\n", torch_tensor, "\n")

# edit the numpy array, obersorve the change in torch tensor, which shares the same memory
numpy_array[0, 0] = 100
print("Edited numpy array:\n", numpy_array)
print("Torch tensor after numpy array edit:\n", torch_tensor, "\n")


# 2. torch tensor to numpy ndarray
print("2. Torch tensor to numpy ndarray:")
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Torch tensor:\n", torch_tensor)
numpy_array = torch_tensor.numpy()
print("Numpy array:\n", numpy_array, "\n")

# edit the torch tensor, obersorve the change in numpy array, which shares the same memory
torch_tensor[0, 0] = 100
print("Edited torch tensor:\n", torch_tensor)
print("Numpy array after torch tensor edit:\n", numpy_array, "\n")


# 3. Notice: not share the same memory (need to copy)
print("3. Use torch.clone() to keep data is independent:")
tensor_independent = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
numpy_independent = tensor_independent.clone().numpy()
print("Torch tensor:\n", tensor_independent)
tensor_independent[0, 0] = 0
print("Edited torch tensor:\n", tensor_independent)
print("Numpy array (independent):\n", numpy_independent, "\n")


1. Numpy ndarray to torch tensor:
Numpy array:
 [[1 2 3]
 [4 5 6]]
Torch tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

Edited numpy array:
 [[100   2   3]
 [  4   5   6]]
Torch tensor after numpy array edit:
 tensor([[100,   2,   3],
        [  4,   5,   6]]) 

2. Torch tensor to numpy ndarray:
Torch tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Numpy array:
 [[1 2 3]
 [4 5 6]] 

Edited torch tensor:
 tensor([[100,   2,   3],
        [  4,   5,   6]])
Numpy array after torch tensor edit:
 [[100   2   3]
 [  4   5   6]] 

3. Use torch.clone() to keep data is independent:
Torch tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Edited torch tensor:
 tensor([[0., 2., 3.],
        [4., 5., 6.]])
Numpy array (independent):
 [[1. 2. 3.]
 [4. 5. 6.]] 

